-- AIanime: Kodik player embed layer.
-- Safe to run repeatedly. Stores iframe/embed player links, not direct HLS/video files.

create table if not exists public.anime_episodes (
  id bigint generated by default as identity primary key,
  anime_slug text not null,
  episode_number int not null default 1,
  title text,
  provider text default 'manual',
  voice text default 'default',
  embed_url text,
  hls_url text,
  duration int,
  status text default 'draft',
  source text default 'manual',
  raw jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(anime_slug, episode_number, provider, voice)
);

create index if not exists anime_episodes_anime_slug_idx on public.anime_episodes(anime_slug);
create index if not exists anime_episodes_status_idx on public.anime_episodes(status);
create index if not exists anime_episodes_episode_idx on public.anime_episodes(episode_number);
create index if not exists anime_episodes_provider_idx on public.anime_episodes(provider);

comment on column public.anime_episodes.embed_url is 'Kodik iframe/embed player URL. AIanime does not store direct video/HLS links by default.';
comment on column public.anime_episodes.hls_url is 'Reserved for licensed/direct providers. Leave null for Kodik embed mode.';
