create table if not exists anime (
  id bigint generated by default as identity primary key,
  shikimori_id bigint unique,
  slug text unique not null,
  title text not null,
  original_title text,
  description text,
  status text,
  kind text,
  year int,
  episodes int default 0,
  rating numeric,
  poster_url text,
  banner_url text,
  genres text[] default '{}',
  studio text,
  provider text default 'jikan',
  raw jsonb default '{}'::jsonb,
  title_ru text,
  title_orig_kodik text,
  other_title text,
  kodik_id text,
  kodik_link text,
  kodik_type text,
  kodik_year integer,
  kodik_shikimori_id bigint,
  translation_id bigint,
  translation_title text,
  translation_type text,
  quality text,
  kodik_screenshots jsonb default '[]'::jsonb,
  kodik_updated_at timestamptz,
  kodik_raw jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

create index if not exists anime_slug_idx on anime(slug);
create index if not exists anime_rating_idx on anime(rating);
create index if not exists anime_year_idx on anime(year);
create index if not exists anime_status_idx on anime(status);

create index if not exists anime_kodik_id_idx on anime(kodik_id);
create index if not exists anime_title_ru_idx on anime(title_ru);
create index if not exists anime_translation_title_idx on anime(translation_title);


create table if not exists anime_players (
  id bigint generated by default as identity primary key,
  anime_slug text not null,
  provider text not null,
  embed_url text,
  voices text[] default '{}',
  quality text[] default '{}',
  raw jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid,
  anime_slug text not null,
  created_at timestamptz default now()
);

create table if not exists watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid,
  anime_slug text not null,
  episode int default 1,
  progress int default 0,
  updated_at timestamptz default now()
);

create table if not exists ai_recommendations (
  id bigint generated by default as identity primary key,
  user_id uuid,
  query text,
  results jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

-- Episodes / future player layer
create table if not exists anime_episodes (
  id bigint generated by default as identity primary key,
  anime_slug text not null,
  episode_number int not null default 1,
  title text,
  provider text default 'manual',
  voice text default 'default',
  embed_url text,
  hls_url text,
  duration int,
  status text default 'draft',
  source text default 'manual',
  raw jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(anime_slug, episode_number, provider, voice)
);

create index if not exists anime_episodes_anime_slug_idx on anime_episodes(anime_slug);
create index if not exists anime_episodes_status_idx on anime_episodes(status);
create index if not exists anime_episodes_episode_idx on anime_episodes(episode_number);
create index if not exists anime_episodes_provider_idx on anime_episodes(provider);

-- User account data tables
create table if not exists user_favorites (
  id bigserial primary key,
  user_id uuid not null,
  anime_slug text not null,
  title text,
  poster text,
  rating text,
  meta text,
  saved_at timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  unique(user_id, anime_slug)
);

create table if not exists user_history (
  id bigserial primary key,
  user_id uuid not null,
  anime_slug text not null,
  title text,
  poster text,
  banner text,
  episode integer default 1,
  progress numeric default 0,
  watched_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique(user_id, anime_slug)
);

create table if not exists user_ratings (
  id bigserial primary key,
  user_id uuid not null,
  anime_slug text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  updated_at timestamp with time zone default now(),
  unique(user_id, anime_slug)
);

create table if not exists user_ai_history (
  id bigserial primary key,
  user_id uuid not null,
  query text not null,
  created_at timestamp with time zone default now()
);

create index if not exists user_favorites_user_idx on user_favorites(user_id);
create index if not exists user_history_user_idx on user_history(user_id);
create index if not exists user_ratings_user_idx on user_ratings(user_id);
create index if not exists user_ai_history_user_idx on user_ai_history(user_id);

alter table user_favorites enable row level security;
alter table user_history enable row level security;
alter table user_ratings enable row level security;
alter table user_ai_history enable row level security;

drop policy if exists "Users can manage own favorites" on user_favorites;
create policy "Users can manage own favorites" on user_favorites
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can manage own history" on user_history;
create policy "Users can manage own history" on user_history
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can manage own ratings" on user_ratings;
create policy "Users can manage own ratings" on user_ratings
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can manage own ai history" on user_ai_history;
create policy "Users can manage own ai history" on user_ai_history
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Jikan / MyAnimeList migration. Safe to run on an existing project.
alter table anime add column if not exists mal_id bigint;
create unique index if not exists anime_mal_id_unique_idx on anime(mal_id) where mal_id is not null;
create index if not exists anime_provider_idx on anime(provider);

comment on column anime.mal_id is 'MyAnimeList id from Jikan API. New primary external id for AIanime catalog.';
comment on column anime.shikimori_id is 'Legacy compatibility column. In Jikan fallback mode it can contain MAL id.';


-- Kodik metadata enrichment. Safe to run on an existing project.
alter table anime add column if not exists title_ru text;
alter table anime add column if not exists title_orig_kodik text;
alter table anime add column if not exists other_title text;
alter table anime add column if not exists kodik_id text;
alter table anime add column if not exists kodik_link text;
alter table anime add column if not exists kodik_type text;
alter table anime add column if not exists kodik_year integer;
alter table anime add column if not exists kodik_shikimori_id bigint;
alter table anime add column if not exists translation_id bigint;
alter table anime add column if not exists translation_title text;
alter table anime add column if not exists translation_type text;
alter table anime add column if not exists quality text;
alter table anime add column if not exists kodik_screenshots jsonb not null default '[]'::jsonb;
alter table anime add column if not exists kodik_updated_at timestamptz;
alter table anime add column if not exists kodik_raw jsonb not null default '{}'::jsonb;
create index if not exists anime_kodik_id_idx on anime(kodik_id);
create index if not exists anime_title_ru_idx on anime(title_ru);
create index if not exists anime_translation_title_idx on anime(translation_title);
